### ISSUE TITLE
Wrong HD generation for recovered wallets

### ISSUE THREAD

**Issue by DaWe35** [siacentral/sia-lite-wallet-web#17]
Hi!

I did 2 tests and received different Sia addresses:

## test 1:

- Opened a new incognito window, recovered `doorway oxygen dummy buying bicycle examine turnip uttered suede noted meant awesome loincloth cottage ablaze ashtray midst ghetto foamy jellyfish gnaw distance often renting stunning dummy bulb unquoted adept`
- Clicked "receive" and got `fc155abce8bf2ea10e666676a9a44a6ad4a9a83775f4b6c98f805337e221971e5c32a307beb3` as 0th address (I can confirm this address is generated with [0,0,0,0,0,0,0,0] index.)
![unknown](https://user-images.githubusercontent.com/10603822/96872313-c42cd880-1473-11eb-8070-2a23eb53e952.png)

## test 2

- I opened a completely new incognito window.
- Generated an address
- Clicked "add wallet" 
![kép](https://user-images.githubusercontent.com/10603822/96872608-21288e80-1474-11eb-8eb9-60071436c2b7.png)

- And I got this as 0th wallet: 
![unknown](https://user-images.githubusercontent.com/10603822/96873183-e70bbc80-1474-11eb-9d10-9e89543742ad.png)
@escada-finance also said that his first wallet was `21ef2a50fd25541c33022f772117552d27a1387601a27d8a5e4dc384506f240028264f56d85b`.
I tried to reproduce it, but after I did it 3 times I was unable to do it again. Now I receive the right address always, does not matter how I recover.

**Comment by n8maninger** [comment]
Each wallet has a unique seed, so generating a new wallet seed should always generate different addresses. Recovering wallet seeds should generate the same address every time. Unless I'm mistaken this is the intended behavior.
