### ISSUE TITLE
Error code 25871

### ISSUE THREAD

**Issue by siatorn** [siacentral/sia-lite-wallet-web#35]
Hi,

I’m getting error code « unknown error 25871 » when trying to import address.

updated java and chrome, closed all orher wallets but still won’t work.

best,

**Comment by n8maninger** [comment]
Is that with a Ledger? These usually fix any issues I have with it
1. unplug your Ledger and close the browser
2. close Ledger Live
3. open the browser and go to lite wallet
4. connect the ledger and try to add the address

If that doesn't work try a different USB cable or port.

**Comment by siatorn** [comment]
Thanks for the response; guess it was either the usb port or I didn't do the things in the right order. 
best,
