### ISSUE TITLE
Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by lapwat** [siacentral/sia-lite-wallet-web#41]
This error happens when I click the Import Public Key button.

- [x] Sia coin app is launched on the ledger.
- [x] Brave browser tab is telling me it is connected to the ledger.

When I click a second time on the button, I have this error:
`Cannot read property 'index' of undefined`

Also when I launch Sia coin app on the ledger, the app closes automatically after 5 seconds.

![2021-08-22-133037_764x392_scrot](https://user-images.githubusercontent.com/7073651/130353455-8e0b1e17-a8f5-4cdc-b2fc-e0379f1794f9.png)

**Comment by n8maninger** [comment]
I can reproduce the issue by first "Rejecting" the key on the device then attempting to generate a new key. I'll get a fix out asap.

These steps worked around it and let me import the public key:
1. Disconnect the Ledger from your PC
2. Refresh the lite wallet
3. Reconnect the Ledger
4. Unlock the device and open the Sia app.
5. Press "Connect" 
6. Press "Import Public Key"
7. "Accept" the key on the Ledger.

**Comment by n8maninger** [comment]
Do you have steps to recreate the ledger app closing after 5 seconds? I cannot recreate that.

**Comment by n8maninger** [comment]
fixed by fbe5ee6

**Comment by lapwat** [comment]
Worked 100% thank you!

**Comment by lapwat** [comment]
Note: My status now showing `Connected v0.4.4` instead of `connected v49.16.0`. Not sure if that matters.

**Comment by lapwat** [comment]
> Do you have steps to recreate the ledger app closing after 5 seconds? I cannot recreate that.

I was because I have not closed the Ledger Desktop App.

**Comment by n8maninger** [comment]
v0.4.4 is correct, v49.16.0 is when you connect without the Sia app open.

**Comment by lapwat** [comment]
Ok all good now!
