### ISSUE TITLE
Display Siafund balances

### ISSUE THREAD

**Issue by harej** [siacentral/sia-lite-wallet-web#5]
While the wallet acknowledges the occurrence of Siafund transactions, it does not display Siafund balances. Instead, you see "Siafund Transaction" as the memo and the transaction is valued at 0 SC.

<img width="619" alt="Screen Shot 2020-07-03 at 5 26 52 PM" src="https://user-images.githubusercontent.com/150027/86501922-648ab000-bd52-11ea-85db-a4621af565a0.png">

<img width="606" alt="Screen Shot 2020-07-03 at 5 27 24 PM" src="https://user-images.githubusercontent.com/150027/86501948-b0d5f000-bd52-11ea-913e-af79dabde34f.png">

**Comment by n8maninger** [comment]
![Screen Shot 2020-07-05 at 08 32 56](https://user-images.githubusercontent.com/5544150/86522520-2ac4c100-be9a-11ea-9a39-828449ebc210.png)

![Screen Shot 2020-07-05 at 08 44 34](https://user-images.githubusercontent.com/5544150/86522629-c60a6600-be9b-11ea-955b-717ed27d64d9.png)

Siafunds will now be displayed on the transactions list and on the transaction details page. Let me know if you run into any issues or inconsistencies, I don't have any Siafunds to test with myself.

**Comment by harej** [comment]
Beautiful, thank you!
